In [1]:
%load_ext autoreload
from path import Path2D
from interpolator import LinearInterpolator, NodeCollection, SplineInterpolator

import numpy as np
import matplotlib.pyplot as plt


In [11]:
%autoreload 2
N = 100
x = np.linspace(0, 100, N)
y = np.ones(N)*30
t = np.linspace(0, 100, len(x))
tmax = t[-1]

nodes = NodeCollection(np.array([x, y]).T, t)
path = Path2D(nodes, SplineInterpolator)

nodes2 = NodeCollection(np.array([x, -y]).T, t)
path2 = Path2D(nodes2, LinearInterpolator)


In [12]:
from radar import RadarGenerator

nprobes = 200
probex = np.linspace(0, 0, nprobes)
probey = np.linspace(0, 0, nprobes)
probetimes = np.linspace(0.1, tmax, nprobes)
probes = np.array([probetimes, probex, probey]).T

radarGen = RadarGenerator([path, path2], 0.1, 1)
measurements = radarGen.make_measurement_series(probes)
msdata = np.array([[ms.x, ms.y] for ms in measurements])

In [ ]:
from filters.jpda import JPDACF
import copy

%matplotlib qt

jpdaf = JPDACF(np.array([30, 0, 0, 0, 0, 0], [0, 0, 0, -30, 0, 0]), 0.1)

dt = 0.05
T = tmax
steps = int(T / dt)

P_k = []
x_k = []
tspace = np.array([])
msrmts = copy.deepcopy(measurements)
t = 0
for i in range(steps):
    t += dt

    kf.predict(dt)
    P_k.append(kf.cov)
    x_k.append(kf.prediction)

    tspace = np.append(tspace, t)

    if (i+1)*dt >= msrmts[0].t:
        kf.update(np.array([msrmts[0].x, msrmts[0].y]), 1, 1)
        P_k.append(kf.cov)
        x_k.append(kf.prediction)
        tspace = np.append(tspace, msrmts[0].t)
        t = msrmts[0].t
        msrmts.pop(0)
        if len(msrmts) == 0:
            break

msdata = np.array([[ms.x, ms.y, ms.t] for ms in measurements])
x = np.array(x_k)[:, 0]
y = np.array(x_k)[:, 3]

plt.figure()
plt.subplot(2, 2, (1, 2))
plt.plot(x, y, color='red')
plt.scatter(x, y, color='red')
plt.scatter(msdata[:, 0], msdata[:, 1], color='blue', s=8)
data = np.array([path.pos(t) for t in np.linspace(0, T, 150)])
plt.plot(data[:, 0], data[:, 1], color='green')

Px = np.array(P_k)[:, 0, 0]
Py = np.array(P_k)[:, 3, 3]
plt.subplot(2, 2, (3))
plt.grid(True)
plt.plot(tspace, x, color='red')
plt.scatter(tspace, x, color='red', s=5)
plt.scatter(msdata[:, 2], msdata[:, 0], color='blue', s=8)
data = np.array([path.pos(t) for t in np.linspace(0, T, 150)])
plt.plot(np.linspace(0, T/dt, 150)*dt, data[:, 0], color='purple')


plt.show()
plt.subplot(2, 2, (4))
plt.plot(tspace, y, color='red')
plt.scatter(msdata[:, 2], msdata[:, 1], color='blue', s=8)
plt.plot(np.linspace(0, T/dt, 150)*dt, data[:, 1], color='purple')


In [ ]:
from filters.kalman import KalmanFilter
import copy

%matplotlib qt

kf = KalmanFilter(np.array([0, 1, 0, 0, 0, 0]), 0.1)

dt = 0.05
T = tmax
steps = int(T / dt)

P_k = []
x_k = []
tspace = np.array([])
msrmts = copy.deepcopy(measurements)
t = 0
for i in range(steps):
    t += dt

    kf.predict(dt)
    P_k.append(kf.cov)
    x_k.append(kf.prediction)

    tspace = np.append(tspace, t)

    if (i+1)*dt >= msrmts[0].t:
        kf.update(np.array([msrmts[0].x, msrmts[0].y]), 1, 1)
        P_k.append(kf.cov)
        x_k.append(kf.prediction)
        tspace = np.append(tspace, msrmts[0].t)
        t = msrmts[0].t
        msrmts.pop(0)
        if len(msrmts) == 0:
            break

msdata = np.array([[ms.x, ms.y, ms.t] for ms in measurements])
x = np.array(x_k)[:, 0]
y = np.array(x_k)[:, 3]

plt.figure()
plt.subplot(2, 2, (1, 2))
plt.plot(x, y, color='red')
plt.scatter(x, y, color='red')
plt.scatter(msdata[:, 0], msdata[:, 1], color='blue', s=8)
data = np.array([path.pos(t) for t in np.linspace(0, T, 150)])
plt.plot(data[:, 0], data[:, 1], color='green')

Px = np.array(P_k)[:, 0, 0]
Py = np.array(P_k)[:, 3, 3]
plt.subplot(2, 2, (3))
plt.grid(True)
plt.plot(tspace, x, color='red')
plt.scatter(tspace, x, color='red', s=5)
plt.scatter(msdata[:, 2], msdata[:, 0], color='blue', s=8)
data = np.array([path.pos(t) for t in np.linspace(0, T, 150)])
plt.plot(np.linspace(0, T/dt, 150)*dt, data[:, 0], color='purple')


plt.show()
plt.subplot(2, 2, (4))
plt.plot(tspace, y, color='red')
plt.scatter(msdata[:, 2], msdata[:, 1], color='blue', s=8)
plt.plot(np.linspace(0, T/dt, 150)*dt, data[:, 1], color='purple')


In [ ]:

jpdaf = JPDACF(np.array([0, 1, 0, 0, 0, 0]), 0.1)

dt = 0.05
T = tmax
steps = int(T / dt)

P_k = []
x_k = []
tspace = np.array([])
msrmts = copy.deepcopy(measurements)
t = 0
for i in range(steps):
    t += dt

    kf.predict(dt)
    P_k.append(kf.cov)
    x_k.append(kf.prediction)

    tspace = np.append(tspace, t)

    if (i+1)*dt >= msrmts[0].t:
        kf.update(np.array([msrmts[0].x, msrmts[0].y]), 1, 1)
        P_k.append(kf.cov)
        x_k.append(kf.prediction)
        tspace = np.append(tspace, msrmts[0].t)
        t = msrmts[0].t
        msrmts.pop(0)
        if len(msrmts) == 0:
            break

msdata = np.array([[ms.x, ms.y, ms.t] for ms in measurements])
x = np.array(x_k)[:, 0]
y = np.array(x_k)[:, 3]

plt.figure()
plt.subplot(2, 2, (1, 2))
plt.plot(x, y, color='red')
plt.scatter(x, y, color='red')
plt.scatter(msdata[:, 0], msdata[:, 1], color='blue', s=8)
data = np.array([path.pos(t) for t in np.linspace(0, T, 150)])
plt.plot(data[:, 0], data[:, 1], color='green')

Px = np.array(P_k)[:, 0, 0]
Py = np.array(P_k)[:, 3, 3]
plt.subplot(2, 2, (3))
plt.grid(True)
plt.plot(tspace, x, color='red')
plt.scatter(tspace, x, color='red', s=5)
plt.scatter(msdata[:, 2], msdata[:, 0], color='blue', s=8)
data = np.array([path.pos(t) for t in np.linspace(0, T, 150)])
plt.plot(np.linspace(0, T/dt, 150)*dt, data[:, 0], color='purple')


plt.show()
plt.subplot(2, 2, (4))
plt.plot(tspace, y, color='red')
plt.scatter(msdata[:, 2], msdata[:, 1], color='blue', s=8)
plt.plot(np.linspace(0, T/dt, 150)*dt, data[:, 1], color='purple')


In [35]:
vec = np.array([1,2,3])
# vec = np.array([[1,2,3], [4,5,6], [7,8,9]])
k = np.kron(np.eye(3), vec)
print(k)

[[1. 2. 3. 0. 0. 0. 0. 0. 0.]
 [4. 5. 6. 0. 0. 0. 0. 0. 0.]
 [7. 8. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 2. 3. 0. 0. 0.]
 [0. 0. 0. 4. 5. 6. 0. 0. 0.]
 [0. 0. 0. 7. 8. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 2. 3.]
 [0. 0. 0. 0. 0. 0. 4. 5. 6.]
 [0. 0. 0. 0. 0. 0. 7. 8. 9.]]
